name: workflow1

on:
  # push:
  #   branches:
  #     - develop
  #     - main
 workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Decir hola
        run: echo "Hola mundo desde workflow 1"