name: workflow2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  automatico:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Decir hola
        run: echo "Hola mundo desde workflow 2"
  manual:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Decir hola
        run: echo "Hola mundo manual desde workflow 2 , sera que da"
  
  