name: Helm Rollback Manual

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Nombre del release de Helm'
        required: true
      revision:
        description: 'Revisión a la que deseas hacer rollback'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer rollback con Helm
        run: |
          echo "Haciendo rollback de ${{ github.event.inputs.release_name }} a la revisión ${{ github.event.inputs.revision }}"
          # helm rollback ${{ github.event.inputs.release_name }} ${{ github.event.inputs.revision }} --namespace tu-namespace
